
export const Doctors=[
    {
        name:"Jane",
        value:"jane"
    }
]


export const Hospitals =[
    {
        name:"Medidcos",
        value:"medidocs"
    }
]

export const Cities =[
    {
        name:"Chennai",
        value:"chennai"
    }
]

export const Gender =[
    {
        name:"Male",
        value:"male"
    },
    {
        name:"Female",
        value:"female"
    },
    {
        name:"Others",
        value:"others"
    },
]


export const Speciality = [
    {
      name: "ENT",
      value: "ent",
    },
    {
      name: "Cardiology",
      value: "cardiology",
    },
    {
      name: "Neurology",
      value: "neurology",
    },
    {
      name: "Orthopedics",
      value: "orthopedics",
    },
    {
      name: "Pediatrics",
      value: "pediatrics",
    },
    {
      name: "Dermatology",
      value: "dermatology",
    },
    {
      name: "Gynecology",
      value: "gynecology",
    },
    {
      name: "Oncology",
      value: "oncology",
    },
    {
      name: "Psychiatry",
      value: "psychiatry",
    },
    {
      name: "Ophthalmology",
      value: "ophthalmology",
    },
    {
      name: "Gastroenterology",
      value: "gastroenterology",
    },
    {
      name: "Nephrology",
      value: "nephrology",
    },
  ];
  

  export const Bookings =[
    {
        name:"All",
        value:"all"
    }
  ]


export const LeadtableData = [
  {
    name: "John Doe",
    contact: "1234567890",
    email: "john.doe@example.com",
    date: "2024-12-02",
    time: "10:00 AM",
    page: "Homepage",
    remarks: "Follow-up required",
    isValid: true,
    addRemarks: "Send email reminder",
    delete: false,
  },
  {
    name: "Jane Smith",
    contact: "9876543210",
    email: "jane.smith@example.com",
    date: "2024-12-01",
    time: "2:00 PM",
    page: "Contact Us",
    remarks: "Issue resolved",
    isValid: true,
    addRemarks: "Thank the user",
    delete: false,
  },
  {
    name: "Alice Johnson",
    contact: "5678901234",
    email: "alice.johnson@example.com",
    date: "2024-11-30",
    time: "9:30 AM",
    page: "Product Page",
    remarks: "Needs follow-up call",
    isValid: false,
    addRemarks: "Call to clarify details",
    delete: false,
  },
  {
    name: "Bob Lee",
    contact: "2345678901",
    email: "bob.lee@example.com",
    date: "2024-12-03",
    time: "11:15 AM",
    page: "About Us",
    remarks: "Happy with service",
    isValid: true,
    addRemarks: "Invite for feedback session",
    delete: false,
  },
  {
    name: "Chris Green",
    contact: "3456789012",
    email: "chris.green@example.com",
    date: "2024-12-04",
    time: "4:00 PM",
    page: "FAQ",
    remarks: "Asked for product details",
    isValid: false,
    addRemarks: "Send brochure via email",
    delete: false,
  },
];



  export const Servicesdata =[
    {
      name:"Home Nurse",
      value:"homenurse"
    },
    {
      name:"Ambulance",
      value:"ambulance"
    },
  ]


  export const Pagesdata=[
    {
      name:"Home",
      value:"home"
    },
  ]

  export const ServicetableData = [
    {
      slno: 1,
      name: "John Doe",
      contact: "1234567890",
      age: 29,
      gender: "Male",
      pCondition: "Healthy",
      location: "New York",
      service: "Consultation",
      date: "2023-12-02",
      time: "10:00 AM",
      bookedTime: "9:30 AM",
    },
    {
      slno: 2,
      name: "Jane Smith",
      contact: "9876543210",
      age: 34,
      gender: "Female",
      pCondition: "Diabetic",
      location: "Los Angeles",
      service: "Follow-up",
      date: "2023-12-03",
      time: "11:00 AM",
      bookedTime: "10:30 AM",
    },
    // Add more rows as needed
  ];


  export const DoctorVisittableData = [
    {
      slNo: 1,
      type: "New",
      booking: "Online",
      name: "John Doe",
      pId: "P12345",
      vId: "V54321",
      phone: "123-456-7890",
      email: "john.doe@example.com",
      date: "2024-12-01",
      time: "10:00 AM",
      bookedTime: "9:45 AM",
      hospital: "Medidocs",
      doctorname: "Jane Smith",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 2,
      type: "Follow-up",
      booking: "Offline",
      name: "Alice Johnson",
      pId: "P12346",
      vId: "V54322",
      phone: "987-654-3210",
      email: "alice.johnson@example.com",
      date: "2024-12-01",
      time: "11:30 AM",
      bookedTime: "11:00 AM",
      hospital: "HealthFirst",
      doctorname: "Dr. Alan",
      status: "Unpaid",
      revisit: "Yes",
      followUpTime: "12:00 PM",
    },
    {
      slNo: 3,
      type: "New",
      booking: "Online",
      name: "Michael Brown",
      pId: "P12347",
      vId: "V54323",
      phone: "654-321-9870",
      email: "michael.brown@example.com",
      date: "2024-12-02",
      time: "09:00 AM",
      bookedTime: "8:30 AM",
      hospital: "MediPlus",
      doctorname: "Dr. Sarah",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 4,
      type: "Follow-up",
      booking: "Offline",
      name: "Emma White",
      pId: "P12348",
      vId: "V54324",
      phone: "321-987-6540",
      email: "emma.white@example.com",
      date: "2024-12-02",
      time: "01:00 PM",
      bookedTime: "12:45 PM",
      hospital: "CareWell",
      doctorname: "Dr. Kevin",
      status: "Paid",
      revisit: "Yes",
      followUpTime: "01:45 PM",
    },
    {
      slNo: 5,
      type: "New",
      booking: "Online",
      name: "Chris Green",
      pId: "P12349",
      vId: "V54325",
      phone: "789-012-3456",
      email: "chris.green@example.com",
      date: "2024-12-03",
      time: "03:00 PM",
      bookedTime: "2:45 PM",
      hospital: "LifeCare",
      doctorname: "Dr. Olivia",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 6,
      type: "Follow-up",
      booking: "Offline",
      name: "Sophia Lee",
      pId: "P12350",
      vId: "V54326",
      phone: "890-123-4567",
      email: "sophia.lee@example.com",
      date: "2024-12-03",
      time: "04:30 PM",
      bookedTime: "4:15 PM",
      hospital: "Wellness Center",
      doctorname: "Dr. Paul",
      status: "Unpaid",
      revisit: "Yes",
      followUpTime: "05:00 PM",
    },
    {
      slNo: 7,
      type: "New",
      booking: "Online",
      name: "James Wilson",
      pId: "P12351",
      vId: "V54327",
      phone: "234-567-8901",
      email: "james.wilson@example.com",
      date: "2024-12-04",
      time: "11:00 AM",
      bookedTime: "10:30 AM",
      hospital: "CityMed",
      doctorname: "Dr. Nancy",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 8,
      type: "Follow-up",
      booking: "Offline",
      name: "Liam Davis",
      pId: "P12352",
      vId: "V54328",
      phone: "456-789-0123",
      email: "liam.davis@example.com",
      date: "2024-12-04",
      time: "02:00 PM",
      bookedTime: "1:45 PM",
      hospital: "HealthHub",
      doctorname: "Dr. Karen",
      status: "Paid",
      revisit: "Yes",
      followUpTime: "02:30 PM",
    },
    {
      slNo: 9,
      type: "New",
      booking: "Online",
      name: "Olivia Martin",
      pId: "P12353",
      vId: "V54329",
      phone: "567-890-1234",
      email: "olivia.martin@example.com",
      date: "2024-12-05",
      time: "09:30 AM",
      bookedTime: "9:15 AM",
      hospital: "MediDocs",
      doctorname: "Dr. Robert",
      status: "Unpaid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 10,
      type: "Follow-up",
      booking: "Offline",
      name: "Ethan Miller",
      pId: "P12354",
      vId: "V54330",
      phone: "678-901-2345",
      email: "ethan.miller@example.com",
      date: "2024-12-05",
      time: "01:30 PM",
      bookedTime: "1:15 PM",
      hospital: "HealthFirst",
      doctorname: "Dr. Angela",
      status: "Paid",
      revisit: "Yes",
      followUpTime: "02:00 PM",
    },
  ];

 export const WalkintableData = [
    {
      slNo: 1,
      type: "New",
      booking: "Online",
      name: "John Doe",
      pId: "P12345",
      vId: "V54321",
      phone: "123-456-7890",
      email: "john.doe@example.com",
      date: "2024-12-01",
      time: "10:00 AM",
      bookedTime: "9:45 AM",
      hospital: "Medidocs",
      doctorname: "Jane Smith",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 2,
      type: "Follow-up",
      booking: "Offline",
      name: "Alice Johnson",
      pId: "P12346",
      vId: "V54322",
      phone: "987-654-3210",
      email: "alice.johnson@example.com",
      date: "2024-12-01",
      time: "11:30 AM",
      bookedTime: "11:00 AM",
      hospital: "HealthFirst",
      doctorname: "Dr. Alan",
      status: "Unpaid",
      revisit: "Yes",
      followUpTime: "12:00 PM",
    },
    {
      slNo: 3,
      type: "New",
      booking: "Online",
      name: "Michael Brown",
      pId: "P12347",
      vId: "V54323",
      phone: "654-321-9870",
      email: "michael.brown@example.com",
      date: "2024-12-02",
      time: "09:00 AM",
      bookedTime: "8:30 AM",
      hospital: "MediPlus",
      doctorname: "Dr. Sarah",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 4,
      type: "Follow-up",
      booking: "Offline",
      name: "Emma White",
      pId: "P12348",
      vId: "V54324",
      phone: "321-987-6540",
      email: "emma.white@example.com",
      date: "2024-12-02",
      time: "01:00 PM",
      bookedTime: "12:45 PM",
      hospital: "CareWell",
      doctorname: "Dr. Kevin",
      status: "Paid",
      revisit: "Yes",
      followUpTime: "01:45 PM",
    },
    {
      slNo: 5,
      type: "New",
      booking: "Online",
      name: "Chris Green",
      pId: "P12349",
      vId: "V54325",
      phone: "789-012-3456",
      email: "chris.green@example.com",
      date: "2024-12-03",
      time: "03:00 PM",
      bookedTime: "2:45 PM",
      hospital: "LifeCare",
      doctorname: "Dr. Olivia",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 6,
      type: "Follow-up",
      booking: "Offline",
      name: "Sophia Lee",
      pId: "P12350",
      vId: "V54326",
      phone: "890-123-4567",
      email: "sophia.lee@example.com",
      date: "2024-12-03",
      time: "04:30 PM",
      bookedTime: "4:15 PM",
      hospital: "Wellness Center",
      doctorname: "Dr. Paul",
      status: "Unpaid",
      revisit: "Yes",
      followUpTime: "05:00 PM",
    },
    {
      slNo: 7,
      type: "New",
      booking: "Online",
      name: "James Wilson",
      pId: "P12351",
      vId: "V54327",
      phone: "234-567-8901",
      email: "james.wilson@example.com",
      date: "2024-12-04",
      time: "11:00 AM",
      bookedTime: "10:30 AM",
      hospital: "CityMed",
      doctorname: "Dr. Nancy",
      status: "Paid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 8,
      type: "Follow-up",
      booking: "Offline",
      name: "Liam Davis",
      pId: "P12352",
      vId: "V54328",
      phone: "456-789-0123",
      email: "liam.davis@example.com",
      date: "2024-12-04",
      time: "02:00 PM",
      bookedTime: "1:45 PM",
      hospital: "HealthHub",
      doctorname: "Dr. Karen",
      status: "Paid",
      revisit: "Yes",
      followUpTime: "02:30 PM",
    },
    {
      slNo: 9,
      type: "New",
      booking: "Online",
      name: "Olivia Martin",
      pId: "P12353",
      vId: "V54329",
      phone: "567-890-1234",
      email: "olivia.martin@example.com",
      date: "2024-12-05",
      time: "09:30 AM",
      bookedTime: "9:15 AM",
      hospital: "MediDocs",
      doctorname: "Dr. Robert",
      status: "Unpaid",
      revisit: "No",
      followUpTime: "-",
    },
    {
      slNo: 10,
      type: "Follow-up",
      booking: "Offline",
      name: "Ethan Miller",
      pId: "P12354",
      vId: "V54330",
      phone: "678-901-2345",
      email: "ethan.miller@example.com",
      date: "2024-12-05",
      time: "01:30 PM",
      bookedTime: "1:15 PM",
      hospital: "HealthFirst",
      doctorname: "Dr. Angela",
      status: "Paid",
      revisit: "Yes",
      followUpTime: "02:00 PM",
    },
  ];